#! /usr/bin/env php
<?php
/**
 * mbp-logging-reports.php
 *
 * A producer to create reports based on logged data in mb-logging-api.
 */

use Symfony\Component\Console\Application;
use DoSomething\MBP_LoggingReports\UserImportCommand;

date_default_timezone_set('America/New_York');
define('CONFIG_PATH',  __DIR__ . '/messagebroker-config');

// Load up the Composer autoload magic
require_once __DIR__ . '/vendor/autoload.php';

$app = new Application('Quicksilver Logging Report Generator', '0.2.1');

$app->add(new UserImportCommand);
$app->run();
